- client/src/components/SidebarNav.js
- package-lock.json
- server/middleware.js
Unnecessary line of code deleted
> Sidebar fix

- client/src/App.js
- client/src/components/SidebarNav.js
- client/src/components/Video.js
> Fixed the error

- .gitignore
> fix mock data

- .gitignore
I removed env file because it should not be in git
> remove env file

- client/src/Header/LoginButton.js
- client/src/LoginPage/BackToHome.js
- client/src/LoginPage/BackToHome.scss
- client/src/LoginPage/LoginForm.js
- client/src/LoginPage/LoginForm.scss
I created a Login form for the Login button in the header, and the login form also contains a back button to return home.
> I created a Login form for the Login button

- package-lock.json
- package.json
- server/db.js
> add dot env and use it to load db credentials

- client/src/Footer/Footer.scss
> Had a mistake in the code, and I've fixed it now

- client/src/App.js
- client/src/SEARCHBAR/SearchBar.js
- client/src/SideBarTest.js
- client/src/components/SidebarNav.js
- package-lock.json
Changes to SearchBar and App.js in respect to route parameters.
> Jan10branchaftersynced

- client/src/Carousel/LanguageCarousel.js
- client/src/Carousel/LanguageCarousel.scss
- server/static/glossarydb.sql
> Carousel links to second page

- client/src/SEARCHBAR/SearchBar.js
- client/src/SEARCHBAR/SearchBar.scss
Pls do not merge it until routing functionality is done
> Search bar styling is done

- client/src/SEARCHBAR/SearchBar.js
- client/src/components/SidebarNav.js
Fixed the filtering issues by language on search and sidebar
> All terms can filter by language and appearing on sidebar by language

- client/src/App.scss
- client/src/components/SidebarNav.js
> small_change_to_CSS_and_sidebarnav_filter

- client/src/components/Video.js
by rendering null when refresh is clicked in the browser.
Made this change because it allows the application to re-render the page
that we are currently on.
> Fixed the issue with routing

- client/src/Header/Header.js
> Home button is functional now

- client/src/App.scss
- client/src/Footer/Footer.scss
Footer is styled and fixed the bottem
> Footer  stayed on bottom

- client/src/components/Video.js
> Language link modified to direct link on the browser

- client/src/index.html
> Changed the title CYF Glossary

- client/src/App.js
- client/src/SEARCHBAR/SearchBar.js
> Adding link to go button

- client/src/App.scss
> Remove background from sidebar

- client/src/Footer/Footer.js
- client/src/components/SidebarNav.js
> added links to footer

- client/src/TermPage/AddTermUserBtn.js
- client/src/TermPage/AddTermUserForm.js
- client/src/TermPage/AddTermUserForm.scss
The submit button has the functionality to accept the input fields.
Gives a submit message and the close window button closes the form
> Added the submit functionality
